### ISSUE TITLE
Prep for 2017

### ISSUE THREAD

**Issue by gassc** [CodeForPittsburgh/fishfrymap#3]
# Goals

* living data separate from map repository
* Public data entry form
* data model that accommodates all possible event information (e.g., times, foods, contacts)

# Tasks

- [x] Set up data model
- [x] Pre-populate with last year's locations
- [ ] ~~Google form for data entry, fusion table on backend for geocoding~~
- [x] Data-entry-a-thon
